 const mongoose = require("mongoose");
// const Tailor = require("./Models/TailorProfile"); // adjust path if needed

// mongoose.connect("mongodb://localhost:27017/yourdbname") // ← change to your DB name
//   .then(() => console.log("Connected"))
//   .catch(err => console.log(err));
var { dbconnect } = require("./Config/DBconfig");
dbconnect();
const Tailor = require("./Models/TailorProfile");
const fs = require("fs");
const path = require("path");
const cloudinary = require("cloudinary").v2;


const tailors = [
  {
    fullName: "Ramesh Sharma",
    email: "ramesh@gmail.com",
    phone: "9876543210",
    city: "Ludhiana",
    gender: "Male",
    dob: "15/03/1985",
    category: "Men",
    specialty: "Suits & Blazers",
    experience: "2005",
    workType: "Shop",
    shopAddress: "12 Model Town Market",
    shopCity: "Ludhiana",
    profileImage: "nopic.jpg",
    aadhaar: "123456789012",
    website: "",
    address: "12 Model Town, Ludhiana",
  },
  {
    fullName: "Sunita Devi",
    email: "sunita@gmail.com",
    phone: "9812345678",
    city: "Delhi",
    gender: "Female",
    dob: "22/07/1990",
    category: "Women",
    specialty: "Bridal Lehenga",
    experience: "2010",
    workType: "Home",
    shopAddress: "",
    shopCity: "",
    profileImage: "nopic.jpg",
    aadhaar: "234567890123",
    website: "instagram.com/sunitatailor",
    address: "Karol Bagh, Delhi",
  },
  {
    fullName: "Arjun Patel",
    email: "arjun@gmail.com",
    phone: "9823456789",
    city: "Mumbai",
    gender: "Male",
    dob: "10/11/1988",
    category: "Both",
    specialty: "Kurta & Sherwani",
    experience: "2008",
    workType: "Both",
    shopAddress: "45 Dharavi Main Road",
    shopCity: "Mumbai",
    profileImage: "nopic.jpg",
    aadhaar: "345678901234",
    website: "",
    address: "Dharavi, Mumbai",
  },
  {
    fullName: "Meena Gupta",
    email: "meena@gmail.com",
    phone: "9834567890",
    city: "Jaipur",
    gender: "Female",
    dob: "05/02/1992",
    category: "Women",
    specialty: "Saree Blouse & Salwar",
    experience: "2012",
    workType: "Home",
    shopAddress: "",
    shopCity: "",
    profileImage: "nopic.jpg",
    aadhaar: "456789012345",
    website: "",
    address: "Mansarovar, Jaipur",
  },
  {
    fullName: "Harpreet Singh",
    email: "harpreet@gmail.com",
    phone: "9845678901",
    city: "Ludhiana",
    gender: "Male",
    dob: "18/09/1983",
    category: "Men",
    specialty: "Pathani & Punjabi Suits",
    experience: "2003",
    workType: "Shop",
    shopAddress: "Ghumar Mandi Chowk",
    shopCity: "Ludhiana",
    profileImage: "nopic.jpg",
    aadhaar: "567890123456",
    website: "",
    address: "Ghumar Mandi, Ludhiana",
  },
  {
    fullName: "Priya Nair",
    email: "priya@gmail.com",
    phone: "9856789012",
    city: "Bangalore",
    gender: "Female",
    dob: "30/04/1995",
    category: "Women",
    specialty: "Designer Blouses",
    experience: "2015",
    workType: "Home",
    shopAddress: "",
    shopCity: "",
    profileImage: "nopic.jpg",
    aadhaar: "678901234567",
    website: "instagram.com/priyastitches",
    address: "Koramangala, Bangalore",
  },
  {
    fullName: "Vikram Yadav",
    email: "vikram@gmail.com",
    phone: "9867890123",
    city: "Lucknow",
    gender: "Male",
    dob: "14/06/1980",
    category: "Both",
    specialty: "Chikan Embroidery Kurta",
    experience: "2000",
    workType: "Shop",
    shopAddress: "Aminabad Market",
    shopCity: "Lucknow",
    profileImage: "nopic.jpg",
    aadhaar: "789012345678",
    website: "",
    address: "Aminabad, Lucknow",
  },
  {
    fullName: "Fatima Sheikh",
    email: "fatima@gmail.com",
    phone: "9878901234",
    city: "Hyderabad",
    gender: "Female",
    dob: "25/12/1991",
    category: "Women",
    specialty: "Anarkali & Party Wear",
    experience: "2011",
    workType: "Both",
    shopAddress: "Laad Bazaar, Charminar",
    shopCity: "Hyderabad",
    profileImage: "nopic.jpg",
    aadhaar: "890123456789",
    website: "instagram.com/fatimafashion",
    address: "Charminar, Hyderabad",
  },
  {
    fullName: "Deepak Joshi",
    email: "deepak@gmail.com",
    phone: "9889012345",
    city: "Delhi",
    gender: "Male",
    dob: "08/01/1987",
    category: "Men",
    specialty: "Wedding Sherwani",
    experience: "2007",
    workType: "Shop",
    shopAddress: "Lajpat Nagar Market",
    shopCity: "Delhi",
    profileImage: "nopic.jpg",
    aadhaar: "901234567890",
    website: "",
    address: "Lajpat Nagar, Delhi",
  },
  {
    fullName: "Kavita Mehta",
    email: "kavita@gmail.com",
    phone: "9890123456",
    city: "Pune",
    gender: "Female",
    dob: "17/08/1993",
    category: "Both",
    specialty: "Indo-Western Fusion",
    experience: "2013",
    workType: "Home",
    shopAddress: "",
    shopCity: "",
    profileImage: "nopic.jpg",
    aadhaar: "012345678901",
    website: "instagram.com/kavitadesigns",
    address: "Kothrud, Pune",
  },
];

Tailor.insertMany(tailors)
  .then(() => {
    console.log("✅ 10 tailor profiles inserted successfully!");
    mongoose.disconnect();
  })
  .catch(err => {
    console.log("❌ Error:", err.message);
    mongoose.disconnect();
  });